// clang has no way to call through a table other than table 0, but its assembler does: module-level assembly declares the two tables
// and uses call_indirect with an explicit table operand.
__asm__(
    ".tabletype table_a, funcref, 1\n"
    "table_a:\n"
    ".tabletype table_b, funcref, 1\n"
    "table_b:\n"
    ".section .text.add1,\"\",@\n"
    ".globl add1\n"
    ".export_name add1, add1\n"
    "add1:\n"
    "  .functype add1 (i32) -> (i32)\n"
    "  local.get 0\n"
    "  i32.const 1\n"
    "  i32.add\n"
    "  end_function\n"
    ".section .text.add100,\"\",@\n"
    ".globl add100\n"
    ".export_name add100, add100\n"
    "add100:\n"
    "  .functype add100 (i32) -> (i32)\n"
    "  local.get 0\n"
    "  i32.const 100\n"
    "  i32.add\n"
    "  end_function\n"
    ".section .text.call_a,\"\",@\n"
    ".globl call_a\n"
    ".export_name call_a, call_a\n"
    "call_a:\n"
    "  .functype call_a (i32) -> (i32)\n"
    "  i32.const 0\n"
    "  ref.func add1\n"
    "  table.set table_a\n"
    "  local.get 0\n"
    "  i32.const 0\n"
    "  call_indirect table_a, (i32) -> (i32)\n"
    "  end_function\n"
    ".section .text.call_b,\"\",@\n"
    ".globl call_b\n"
    ".export_name call_b, call_b\n"
    "call_b:\n"
    "  .functype call_b (i32) -> (i32)\n"
    "  i32.const 0\n"
    "  ref.func add100\n"
    "  table.set table_b\n"
    "  local.get 0\n"
    "  i32.const 0\n"
    "  call_indirect table_b, (i32) -> (i32)\n"
    "  end_function\n");
