// Integration score and combined score. Reads results/integration.json (cells), the verdicts, results/integration/size.json (I5),
// results/rating/weights.json (obstacle factors), results/rating/integration-weights.json (route factors, criterion weights, split) and
// results/rating/rating.json (exposure scores). Writes results/integration/rating.md and rating.json.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { LANG_KEYS } from './cells.mjs';

const coding = JSON.parse(readFileSync('results/integration.json', 'utf8'));
const W = JSON.parse(readFileSync('results/rating/weights.json', 'utf8'));
const IW = JSON.parse(readFileSync('results/rating/integration-weights.json', 'utf8'));
const size = JSON.parse(readFileSync('results/integration/size.json', 'utf8'));
const exposure = Object.fromEntries(JSON.parse(readFileSync('results/rating/rating.json', 'utf8')).languages.map((l) => [l.id, l.score]));
const obstacle = Object.fromEntries(W.obstacles.map((o) => [o.kind, o.factor]));
const CRITERIA = Object.keys(IW.criteria);
const NAMES = { I1: 'WASI', I2: 'Component Model', I3: 'JS bindings', I4: 'Debuggability', I5: 'Size' };

// cell score of one variant, given route factors
const variantScore = (r, routeF) => (r.support === 'partial' ? 0.5 : 1) * routeF[r.route] * (r.needs ?? []).reduce((p, n) => p * obstacle[n], 1);
const cellScore = (cell, routeF) => (!cell || cell.absent ? 0 : Math.max(...Object.values(cell.variants).map((r) => variantScore(r, routeF))));

function scores(routeF, weights, split) {
  const out = {};
  for (const lang of LANG_KEYS) {
    const per = {};
    for (const c of CRITERIA) per[c] = c === 'I5' ? size.score[lang] ?? 0 : cellScore(coding[lang]?.[c], routeF);
    const wsum = CRITERIA.reduce((s, c) => s + weights[c], 0);
    const integration = CRITERIA.reduce((s, c) => s + weights[c] * per[c], 0) / wsum;
    out[lang] = { per, integration, combined: split.exposure * exposure[lang] + split.integration * integration };
  }
  return out;
}
// which variant stands for each cell (the highest score), for the tooltips of the chart
const best = (cell) => {
  if (!cell) return { absent: 'none' };
  if (cell.absent) return { absent: cell.absent };
  const [name, r] = Object.entries(cell.variants).map(([n, v]) => [n, v]).sort((a, b) => variantScore(b[1], routeF0) - variantScore(a[1], routeF0))[0];
  return { variant: name, route: r.route, support: r.support, tools: r.tools ?? [], needs: r.needs ?? [], missing: r.missing };
};
const routeF0 = Object.fromEntries(IW.routes.map((r) => [r.kind, r.factor]));
const base = scores(routeF0, IW.criteria, IW.combined);
const detail = Object.fromEntries(LANG_KEYS.map((l) => [l, Object.fromEntries(CRITERIA.map((c) => [c, c === 'I5' ? { sizeScore: size.score[l] } : best(coding[l]?.[c])]))]));
const rank = (s, key) => Object.keys(s).sort((a, b) => s[b][key] - s[a][key]);

// sensitivity: route factors perturbed (their order kept), criterion weights x U(0.5, 1.5), split exposure in U(0.4, 0.8)
let seed = 20261009; const rnd = () => { seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0; return seed / 2 ** 32; };
const N = 2000, wins = {}, ranks = Object.fromEntries(LANG_KEYS.map((l) => [l, []]));
const pair = {};
const kinds = IW.routes.map((r) => r.kind);
for (let i = 0; i < N; i++) {
  const f = kinds.map((k) => Math.min(1, routeF0[k] * (0.8 + 0.4 * rnd()))).sort((a, b) => b - a);
  f[0] = 1; // builtin stays 1; the order of the others is kept by sorting
  const routeF = Object.fromEntries(kinds.map((k, j) => [k, f[j]]));
  const weights = Object.fromEntries(CRITERIA.map((c) => [c, IW.criteria[c] * (0.5 + rnd())]));
  const e = 0.4 + 0.4 * rnd();
  const s = scores(routeF, weights, { exposure: e, integration: 1 - e });
  const r = rank(s, 'combined');
  r.forEach((l, j) => ranks[l].push(j + 1));
  for (const a of LANG_KEYS) for (const b of LANG_KEYS) if (a < b) { const k = `${a}|${b}`; pair[k] = (pair[k] ?? 0) + (s[a].combined > s[b].combined ? 1 : 0); }
}
const order = rank(base, 'combined');
const pct = (n) => `${Math.round((100 * n) / N)}%`;
const share = (a, b) => (a < b ? pair[`${a}|${b}`] : N - pair[`${b}|${a}`]);

const f2 = (x) => x.toFixed(2);
const md = ['# Integration rating', '', 'Generated by `check/integration-rating.mjs`. Coefficients in `results/rating/integration-weights.json`; obstacle factors from `results/rating/weights.json`.', '',
  '## Scores', '', `| Language | ${CRITERIA.map((c) => `${c} ${NAMES[c]}`).join(' | ')} | Integration | Exposure | Combined (${IW.combined.exposure}/${IW.combined.integration}) | Rank (best–worst in ${N} runs) |`, `|---|${CRITERIA.map(() => '---').join('|')}|---|---|---|---|`,
  ...order.map((l) => `| ${l} | ${CRITERIA.map((c) => f2(base[l].per[c])).join(' | ')} | ${f2(base[l].integration)} | ${f2(exposure[l])} | **${f2(base[l].combined)}** | ${Math.min(...ranks[l])}–${Math.max(...ranks[l])} |`), '',
  '## Is the order robust?', '', 'Share of runs in which each language beats the next one in the order (route factors perturbed with their order kept, criterion weights x 0.5–1.5, exposure share 0.4–0.8). Robust at ≥ 95%.', '',
  '| Ahead | Behind | Share | Robust |', '|---|---|---|---|', ...order.slice(0, -1).map((a, i) => { const b = order[i + 1]; const s = share(a, b); return `| ${a} | ${b} | ${pct(s)} | ${s / N >= 0.95 ? 'yes' : 'no'} |`; }), ''].join('\n');
writeFileSync('results/integration/rating.md', md);
writeFileSync('results/integration/rating.json', JSON.stringify({ about: 'Integration and combined scores, 0..1. per = score of each criterion.', weights: IW, criteria: Object.fromEntries(CRITERIA.map((c) => [c, { name: NAMES[c], weight: IW.criteria[c], ...IW.info?.[c] }])), languages: LANG_KEYS.map((l) => ({ id: l, detail: detail[l], ...base[l], exposure: exposure[l], rank: { best: Math.min(...ranks[l]), worst: Math.max(...ranks[l]) } })) }, null, 1));
console.log(md);
