// Usage: node check/matrix.mjs
// Renders results/matrix.md from results/coding.json (the hand-authored classification of each cell, loaded and checked by
// cells.mjs): every cell must exist, use the agreed vocabulary, and point at probe directories (or an ABSENT.md) that exist.
// Where a cell rests on a probe, the checker's verdict for it is printed next to it. Nothing here is a result by itself: the coding
// is a judgement over the verdicts, and the verdicts are in results/<lang>/*.json. The rating (check/rating.mjs) reads the same file.
import { writeFileSync, existsSync, readdirSync } from 'node:fs';
import { FEATURES as FEATURE_LIST } from './feature-list.mjs';
import { loadCells, cellLabel, verdictOf, dirsOf, probeText } from './cells.mjs';

const LANGS = [['rust', 'Rust'], ['zig', 'Zig'], ['c', 'C'], ['moonbit', 'MoonBit'], ['assemblyscript', 'AssemblyScript'], ['tinygo', 'TinyGo'], ['kotlin', 'Kotlin'], ['swift', 'Swift']];
const { cells, problems, caveats } = loadCells();
if (problems.length) { console.error(problems.join('\n')); process.exit(1); }

const lines = [];
lines.push('# Results matrix (generated)', '', 'Generated by `node check/matrix.mjs` from `results/coding.json` and the verdicts in `results/<lang>/*.json`.',
  'The coding is a judgement over the verdicts (vocabulary: see `../chapter-2-test-matrix.md`); the verdicts are the evidence. Review both.', '',
  '| # | Feature | ' + LANGS.map(([, n]) => n).join(' | ') + ' |', '|---|---|' + LANGS.map(() => '---').join('|') + '|');
for (const { id, name } of FEATURE_LIST) lines.push(`| ${id} | ${name} | ${LANGS.map(([lang]) => cellLabel(cells[lang][id])).join(' | ')} |`);

const caveatLines = LANGS.filter(([lang]) => caveats[lang]?.length).flatMap(([lang, n]) => caveats[lang].map((t) => `- **${n}**: ${t}`));
if (caveatLines.length) lines.push('', '## Language caveats', '', 'True of every probe of the language, so not repeated in each cell and not counted against any one feature.', '', ...caveatLines);

lines.push('', '## Evidence per cell', '', 'For each cell: the coding, the probe variants it rests on with the checker\'s verdict for each, and the note.', '');
const verdict = (dir, id, name, shown) => `\`${shown}\` (${verdictOf(dir, id, name) ?? 'no verdict'})`;
for (const [lang, langName] of LANGS) {
  lines.push(`### ${langName}`, '');
  for (const { id, name, slug } of FEATURE_LIST) {
    const c = cells[lang][id];
    if (c.pending) { lines.push(`- **${id} ${name}**: not yet probed.`); continue; }
    const restsOn = c.absent ? c.restsOn : c.selected.probes;
    const used = new Set(restsOn.map((r) => `${r.dir}/${r.name}`));
    const others = dirsOf(lang).flatMap((d) => { const base = `probes/${id}-${slug}/${d}`;
      return existsSync(base) ? readdirSync(base, { withFileTypes: true }).filter((e) => e.isDirectory() && !used.has(`${d}/${e.name}`)).map((e) => verdict(d, id, e.name, probeText(lang, { dir: d, name: e.name }))) : []; });
    lines.push(`- **${id} ${name}**: ${cellLabel(c)}.`
      + (restsOn.length ? ` Rests on ${restsOn.map((r) => verdict(r.dir, id, r.name, probeText(lang, r))).join(', ')}.`
         : ` No probe; what was checked is in ${c.absentFiles.map((f) => `[\`${f}\`](../${f})`).join(', ')}.`)
      + (others.length ? ` Other attempts: ${others.join(', ')}.` : '') + (c.note ? ` ${c.note}` : ''));
  }
  lines.push('');
}
writeFileSync('results/matrix.md', lines.join('\n'));
console.log('results/matrix.md written');
