// Inlines results/rating/rating.json and results/integration/rating.json into viz/data.js so index.html works when
// opened straight from disk (browsers block fetch() on file:// URLs).
//
//   node viz/build-data.mjs
//
// Both are generated (`make rating`, `make integration-rating`); re-run this after either changes.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, '..', 'results', 'rating', 'rating.json');
const target = join(here, 'data.js');
const integrationSource = join(here, '..', 'results', 'integration', 'rating.json');

const rating = JSON.parse(readFileSync(source, 'utf8'));
const banner = '// Generated by viz/build-data.mjs from results/rating/rating.json. Do not edit by hand.\n';
const integration = JSON.parse(readFileSync(integrationSource, 'utf8'));
integration.toolchain = JSON.parse(readFileSync(join(here, '..', 'results', 'integration', 'i6.json'), 'utf8')).languages;
writeFileSync(target, `${banner}window.RATING = ${JSON.stringify(rating)};\nwindow.INTEGRATION = ${JSON.stringify(integration)};\n`);
console.log(`wrote ${target} (${rating.languages.length} languages, ${rating.cells.length} cells)`);
