// Inlines results/rating/rating.json into viz/data.js so index.html works when
// opened straight from disk (browsers block fetch() on file:// URLs).
//
//   node viz/build-data.mjs
//
// rating.json is generated (`make rating`); re-run this after it changes.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, '..', 'results', 'rating', 'rating.json');
const target = join(here, 'data.js');

const rating = JSON.parse(readFileSync(source, 'utf8'));
const banner = '// Generated by viz/build-data.mjs from results/rating/rating.json. Do not edit by hand.\n';
writeFileSync(target, `${banner}window.RATING = ${JSON.stringify(rating)};\n`);
console.log(`wrote ${target} (${rating.languages.length} languages, ${rating.cells.length} cells)`);
