// clang's builtins have no null test for a funcref, but its assembler does: module-level assembly does the whole task.
__asm__(
    ".tabletype t, funcref, 1\n"
    "t:\n"
    ".section .text.f,\"\",@\n"
    ".globl f\n"
    ".export_name f, f\n"
    "f:\n"
    "  .functype f () -> ()\n"
    "  end_function\n"
    ".section .text.table_ops,\"\",@\n"
    ".globl table_ops\n"
    ".export_name table_ops, table_ops\n"
    "table_ops:\n"
    "  .functype table_ops (i32) -> (i32)\n"
    "  ref.null_func\n"
    "  local.get 0\n"
    "  table.grow t\n"
    "  drop\n"
    "  i32.const 1\n"
    "  ref.func f\n"
    "  table.set t\n"
    "  table.size t\n"
    "  i32.const 2\n"
    "  table.get t\n"
    "  ref.is_null\n"
    "  i32.const 100\n"
    "  i32.mul\n"
    "  i32.add\n"
    "  i32.const 1\n"
    "  table.get t\n"
    "  ref.is_null\n"
    "  i32.eqz\n"
    "  i32.const 1000\n"
    "  i32.mul\n"
    "  i32.add\n"
    "  end_function\n");
