__asm__(
    ".section .text.twice,\"\",@\n"
    ".globl twice\n"
    ".export_name twice, twice\n"
    "twice:\n"
    "  .functype twice (i32) -> (i32)\n"
    "  local.get 0\n"
    "  i32.const 2\n"
    "  i32.mul\n"
    "  end_function\n"
    ".section .text.apply,\"\",@\n"
    ".globl apply\n"
    ".export_name apply, apply\n"
    "apply:\n"
    "  .functype apply (i32) -> (i32)\n"
    "  local.get 0\n"
    "  ref.func twice\n"
    "  call_ref (i32) -> (i32)\n"
    "  end_function\n");
